Repository wecode-bootcamp-korea/39-2nd-VVolt-Market-frontend, pull requests merged in 2022-12, with the labels that each got.

#4 [39기 심동섭]ADD: FOOTER구현
  public/images/profile_img_1.png
  public/images/profile_img_2.png
  public/images/profile_img_3.png
  public/images/profile_img_4.png
  public/images/profile_img_5.png
  public/images/profile_img_6.png
  public/images/profile_img_7.png
  src/components/Footer/Footer.js
Labels: 멘토 리뷰 요청

#5 [39기 강지민] ADD: 상품등록페이지 레이아웃 구현
  src/pages/ProductRegister/ProductRegister.js
Labels: 멘토 리뷰 요청

#2 [39기 강지민] ADD: login 페이지 구현
  .gitignore
  src/Router.js
  src/pages/Login/KakaoLogin.js
  src/pages/Login/Login.js
  src/pages/Login/components/OAuth.js
Labels: 멘토 리뷰 요청

#3 [39기 심동섭] ADD: 상품리스트 기능구현(백엔드 테스트 전)
  public/data/productsInfo.json
  public/index.html
  src/Router.js
  src/pages/ProductList/ListItem.js
  src/pages/ProductList/ProductList.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#10 [39기 조은혜] ADD:상품상세페이지 레이아웃 완료
  public/data/productDetail.json
  src/assets/images/heart.png
  src/assets/images/hour.png
  src/assets/images/icon_star_score.png
  src/assets/images/icon_star_score_bg.png
  src/assets/images/localicon.png
  src/assets/images/view.png
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#13 [39기 강지민] ADD: login page loading 화면 구현
  src/pages/Login/KakaoLogin.js
Labels: 멘토 리뷰 요청

#6 [39기 정효원] Add: 회원가입 페이지 레이아웃 / 기능 구현 완료
  package-lock.json
  package.json
  public/index.html
  src/pages/Signup/SearchAddress/PopupDom.js
  src/pages/Signup/SearchAddress/PopupPostCode.js
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#7 [39기 강지민] ADD: 상품등록페이지 기능 구현
  src/pages/Login/KakaoLogin.js
  src/pages/Login/components/OAuth.js
  src/pages/ProductRegister/ProductRegister.js
Labels: 멘토 리뷰 요청

#8 [39기 조은혜] ADD: nav바 구현
  public/images/loginicion.png
  public/images/mainlogo.png
  public/images/mystoreicon.png
  public/images/searchicon.png
  public/images/sellicon.png
  public/images/starlogo.png
  public/images/switch.png
  public/images/tabimg.png
  public/images/tabimg2.png
  src/assets/images/mainlogo.png
  src/components/Nav/Nav.js
Labels: 수정 요청

#11 [39기 조은혜] ADD: 사이드바 레이아웃
  public/data/sideBar.json
  src/assets/images/heart2.png
  src/assets/images/qrcode.png
  src/components/SideBar/SideBar.js
Labels: 멘토 리뷰 요청

#14 [39기 조은혜] ADD : 상품 상세페이지 기능 구현
  public/data/productDetail.json
  src/assets/images/heartbtn.png
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#15 [39기 심동섭 ]ADD : merge Test
  package-lock.json
  public/data/storeInfo.json
  public/images/mainlogo.png
  public/images/searchicon.png
  public/images/slideImg1.png
  public/images/slideImg2.png
  public/images/slideImg3.png
  public/images/slideImg4.png
  public/images/tabimg2.png
  public/index.html
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/components/SideBar/SideBar.js
  src/config.js
  src/pages/Login/KakaoLogin.js
  src/pages/Login/Login.js
  src/pages/Payment/Payment.js
  src/pages/Payment/PaymentSuccess.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/ListItem.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductRegister/ProductRegister.js
  src/pages/Signup/Signup.js
  src/pages/Store/FollowUser.js
  src/pages/Store/Store.js
  src/pages/Store/StoreFollow.js
  src/pages/Store/StoreListItem.js
  src/pages/Store/StoreProducts.js
  src/pages/Store/StoreReviews.js
  src/pages/Store/StroeEachReivew.js
Labels: 멘토 리뷰 요청
